/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/servicefwmark/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/servicefwmark/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceFWMarksGetter has a method to return a ServiceFWMarkInterface.
// A group's client should implement this interface.
type ServiceFWMarksGetter interface {
	ServiceFWMarks(namespace string) ServiceFWMarkInterface
}

// ServiceFWMarkInterface has methods to work with ServiceFWMark resources.
type ServiceFWMarkInterface interface {
	Create(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.CreateOptions) (*v1.ServiceFWMark, error)
	Update(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.UpdateOptions) (*v1.ServiceFWMark, error)
	UpdateStatus(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.UpdateOptions) (*v1.ServiceFWMark, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ServiceFWMark, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ServiceFWMarkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceFWMark, err error)
	ServiceFWMarkExpansion
}

// serviceFWMarks implements ServiceFWMarkInterface
type serviceFWMarks struct {
	client rest.Interface
	ns     string
}

// newServiceFWMarks returns a ServiceFWMarks
func newServiceFWMarks(c *K8sV1Client, namespace string) *serviceFWMarks {
	return &serviceFWMarks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceFWMark, and returns the corresponding serviceFWMark object, and an error if there is any.
func (c *serviceFWMarks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceFWMark, err error) {
	result = &v1.ServiceFWMark{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicefwmarks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceFWMarks that match those selectors.
func (c *serviceFWMarks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceFWMarkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ServiceFWMarkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicefwmarks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceFWMarks.
func (c *serviceFWMarks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicefwmarks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceFWMark and creates it.  Returns the server's representation of the serviceFWMark, and an error, if there is any.
func (c *serviceFWMarks) Create(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.CreateOptions) (result *v1.ServiceFWMark, err error) {
	result = &v1.ServiceFWMark{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicefwmarks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceFWMark).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceFWMark and updates it. Returns the server's representation of the serviceFWMark, and an error, if there is any.
func (c *serviceFWMarks) Update(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.UpdateOptions) (result *v1.ServiceFWMark, err error) {
	result = &v1.ServiceFWMark{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicefwmarks").
		Name(serviceFWMark.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceFWMark).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *serviceFWMarks) UpdateStatus(ctx context.Context, serviceFWMark *v1.ServiceFWMark, opts metav1.UpdateOptions) (result *v1.ServiceFWMark, err error) {
	result = &v1.ServiceFWMark{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicefwmarks").
		Name(serviceFWMark.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceFWMark).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceFWMark and deletes it. Returns an error if one occurs.
func (c *serviceFWMarks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicefwmarks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceFWMarks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicefwmarks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceFWMark.
func (c *serviceFWMarks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceFWMark, err error) {
	result = &v1.ServiceFWMark{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicefwmarks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
