/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressqos/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressqos/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressQoSesGetter has a method to return a EgressQoSInterface.
// A group's client should implement this interface.
type EgressQoSesGetter interface {
	EgressQoSes(namespace string) EgressQoSInterface
}

// EgressQoSInterface has methods to work with EgressQoS resources.
type EgressQoSInterface interface {
	Create(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.CreateOptions) (*v1.EgressQoS, error)
	Update(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.UpdateOptions) (*v1.EgressQoS, error)
	UpdateStatus(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.UpdateOptions) (*v1.EgressQoS, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressQoS, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressQoSList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressQoS, err error)
	EgressQoSExpansion
}

// egressQoses implements EgressQoSInterface
type egressQoses struct {
	client rest.Interface
	ns     string
}

// newEgressQoSes returns a EgressQoSes
func newEgressQoSes(c *K8sV1Client, namespace string) *egressQoses {
	return &egressQoses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the egressQos, and returns the corresponding egressQos object, and an error if there is any.
func (c *egressQoses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressQoS, err error) {
	result = &v1.EgressQoS{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressqoses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressQoSes that match those selectors.
func (c *egressQoses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressQoSList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressQoSList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressqoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressQoses.
func (c *egressQoses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("egressqoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressQos and creates it.  Returns the server's representation of the egressQos, and an error, if there is any.
func (c *egressQoses) Create(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.CreateOptions) (result *v1.EgressQoS, err error) {
	result = &v1.EgressQoS{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("egressqoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressQos).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressQos and updates it. Returns the server's representation of the egressQos, and an error, if there is any.
func (c *egressQoses) Update(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.UpdateOptions) (result *v1.EgressQoS, err error) {
	result = &v1.EgressQoS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressqoses").
		Name(egressQos.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressQos).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *egressQoses) UpdateStatus(ctx context.Context, egressQos *v1.EgressQoS, opts metav1.UpdateOptions) (result *v1.EgressQoS, err error) {
	result = &v1.EgressQoS{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressqoses").
		Name(egressQos.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressQos).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressQos and deletes it. Returns an error if one occurs.
func (c *egressQoses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressqoses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressQoses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressqoses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressQos.
func (c *egressQoses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressQoS, err error) {
	result = &v1.EgressQoS{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("egressqoses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
